config/routes.rb
MvcReader::Application.routes.draw do
  resources :post_read_records
  resources :rss_posts
  resources :rss_feeds
  
  match 'users/signin', :to => "users#signin"  
  resources :users
  resources :subscriptions

  

  get "home/index"

  root :to => "home#index"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :rss_feed
  attr_accessible :rss_feed
  attr_accessible :feed_url
  
  def feed_url
    if self.rss_feed_id.nil? then ""
    else RssFeed.find(self.rss_feed_id).url
    end
  end
  
  def feed_url=(url)
    rss_feed = RssFeed.where(:url => url)[0]
    if rss_feed.nil? then
      rss_feed = RssFeed.create(:url => url)
    end
    old_feed_id = self.rss_feed_id
    self.rss_feed_id = rss_feed.id
    save
    if not old_feed_id.nil? then
      RssFeed.find(old_feed_id).cleanup_unused
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
#    logger.debug "Creating subscription for user #{@user.id}"
    @user = User.find(params[:subscription][:user_id])
    @subscription = @user.subscriptions.create(params[:subscription])
    @subscription.feed_url=params[:subscription][:feed_url]    
    redirect_to user_path(@user)
  end
  
  def destroy
    @subscription = Subscription.find(params[:id])
    @user = User.find(@subscription.user_id)
    rss_feed_id = @subscription.rss_feed_id
    @subscription.destroy
    @subscription.save
    RssFeed.find(rss_feed_id).cleanup_unused
    redirect_to user_path(@user)
  end
  
  def show
    @subscription = Subscription.find(params[:id])
    @user = User.find(@subscription.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

# PUT /subscriptions/1
# PUT /subscriptions/1.xml
  def update
    @subscription = Subscription.find(params[:id])
    @user = User.find(@subscription.user_id)
    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to(@user, :notice => 'Subscription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # GET /users/1/subscriptions/new
  # GET /users/1/subscriptions/new.xml
  def new
    @user = User.find(params[:user_id])
    @subscription = @user.subscriptions.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_form.html.erb
<%= form_for @subscription do |f| %>

<% if false %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>


	<%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<table border=0>
	<tr>
		<td>
			<%= render :partial => "rss_feeds/rss_feed_header", :locals => { :rss_feed_id => subscription.rss_feed_id, :user_id => subscription.user_id } %>
		</td>
		<td>
			<%= link_to image_tag("read.png", :border => 0),
			 		subscription_path(subscription.id) %>
			<%= link_to image_tag("edit.png", :border => 0),
					edit_subscription_path(subscription.id) %>
										
			<%= link_to image_tag("trash.png", :border => 0),
					subscription,
					:confirm => 'Are you sure?',
					:method => :delete %>
		</td>
	</tr>
</table>
<hr />

app/views/subscriptions/edit.html.erb
<%= link_to "Sign in as a different user", users_signin_path %>
<%= link_to "Go Back", user_path(@subscription.user_id) %>
<hr>

<h1>Editing subscription</h1>
<% @user = User.find(@subscription.user_id)%>
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<%= link_to "Sign in as a different user", users_signin_path %>
<%= link_to "Go Back", user_path(@subscription.user_id) %>
<hr>

<p id="notice"><%= notice %></p>

<%= render :partial => "rss_feeds/rss_feed_header", :locals => { :rss_feed_id => @subscription.rss_feed_id, :user_id => @subscription.user_id } %>
<hr>
<%= render :partial => "rss_feeds/feed", :locals => { :rss_feed_id => @subscription.rss_feed_id, :user_id => @subscription.user_id } %>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>