config/routes.rb
MvcReader::Application.routes.draw do
  resources :post_read_records
  resources :rss_posts
  resources :rss_feeds
  
  match 'users/signin', :to => "users#signin"  
  resources :users
  resources :subscriptions

  

  get "home/index"

  root :to => "home#index"

end

app/models/rss_feed.rb
require 'rss/1.0'
require 'rss/2.0'

class RssFeed < ActiveRecord::Base
  has_many :rss_posts, :dependent => :destroy
  has_many :subscriptions
  #validates_uniqueness_of :url
  
  def get_latest_feed
    logger.debug "updating RssFeed id #{self.id}"
    content = ""
    begin
      open(self.url) do |s| content = s.read end
    rescue
      self.title = "ERROR connecting to this feed"
      self.description = "Check the URL of the feed and make any necessary corrections"
      logger.debug "ERROR getting feed from url #{self.url}"
      save
      return
    end
    begin
      rss = RSS::Parser.parse(content, false)
      self.title = rss.channel.title
      self.description = rss.channel.description
      rss.items.each do |item| 
        if RssPost.where(:link => item.link).length == 0 then 
          RssPost.create(:rss_feed_id => self.id, 
                         :title => item.title,
                         :link => item.link,
                         :description => item.description)
        end
      end
    rescue
      self.title = "ERROR parsing feed"
      self.description = "Check the URL of the feed and that the feed is RSS compliant"
    end
    save
  end
  
  def cleanup_unused
    subscriptions = Subscription.where( :rss_feed_id => self.id)
    if subscriptions.length == 0 then
      destroy
    end
  end
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  # GET /rss_feeds/1/edit
  def edit
    @rss_feed = RssFeed.find(params[:id])
  end

  # POST /rss_feeds
  # POST /rss_feeds.xml
  def create
    @rss_feed = RssFeed.new(params[:rss_feed])

    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to(@rss_feed, :notice => 'Rss feed was successfully created.') }
        format.xml  { render :xml => @rss_feed, :status => :created, :location => @rss_feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rss_feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rss_feeds/1
  # PUT /rss_feeds/1.xml
  def update
    @rss_feed = RssFeed.find(params[:id])

    respond_to do |format|
      if @rss_feed.update_attributes(params[:rss_feed])
        format.html { redirect_to(@rss_feed, :notice => 'Rss feed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rss_feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.xml
  def destroy
    @rss_feed = RssFeed.find(params[:id])
    @rss_feed.destroy

    respond_to do |format|
      format.html { redirect_to(rss_feeds_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/rss_feeds/_feed.html.erb
<% RssPost.where(:rss_feed_id => rss_feed_id).each do |post| %>
	<% unread = PostReadRecord.where(:rss_post_id => post.id, :user_id => user_id).length == 0 %>
	<% if unread then %>
	<b>
	<% end %>
	<%= render :partial => "rss_posts/link", :locals => { :post => post, :user_id => user_id } %>
	<% if unread then %>
	</b>
	<% end %>
 	<br />
<% end %>

app/views/rss_feeds/_form.html.erb
<%= form_for(@rss_feed) do |f| %>
  <% if @rss_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed.errors.count, "error") %> prohibited this rss_feed from being saved:</h2>

      <ul>
      <% @rss_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rss_feeds/_rss_feed_header.html.erb
<% feed = RssFeed.find(rss_feed_id) %>
<% feed.get_latest_feed() %>
<b> <%= feed.title %> </b> <br />
<%= feed.description %> <br />
<i><%= feed.url %></i>

app/views/rss_feeds/edit.html.erb
<h1>Editing rss_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @rss_feed %> |
<%= link_to 'Back', rss_feeds_path %>