config/routes.rb
MvcReader::Application.routes.draw do
  resources :post_read_records
  resources :rss_posts
  resources :rss_feeds
  
  match 'users/signin', :to => "users#signin"  
  resources :users
  resources :subscriptions

  

  get "home/index"

  root :to => "home#index"

end

app/models/rss_post.rb
class RssPost < ActiveRecord::Base
  belongs_to :rss_feed
  has_many :post_read_records
end

app/controllers/rss_posts_controller.rb
class RssPostsController < ApplicationController
  # GET /rss_posts
  # GET /rss_posts.xml
  def index
    @rss_posts = RssPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rss_posts }
    end
  end

  # GET /rss_posts/1
  # GET /rss_posts/1.xml
  def show
    @rss_post = RssPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rss_post }
    end
  end

  # GET /rss_posts/new
  # GET /rss_posts/new.xml
  def new
    @rss_post = RssPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rss_post }
    end
  end

  # GET /rss_posts/1/edit
  def edit
    @rss_post = RssPost.find(params[:id])
  end

  # POST /rss_posts
  # POST /rss_posts.xml
  def create
    @rss_post = RssPost.new(params[:rss_post])

    respond_to do |format|
      if @rss_post.save
        format.html { redirect_to(@rss_post, :notice => 'Rss post was successfully created.') }
        format.xml  { render :xml => @rss_post, :status => :created, :location => @rss_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rss_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rss_posts/1
  # PUT /rss_posts/1.xml
  def update
    @rss_post = RssPost.find(params[:id])

    respond_to do |format|
      if @rss_post.update_attributes(params[:rss_post])
        format.html { redirect_to(@rss_post, :notice => 'Rss post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rss_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_posts/1
  # DELETE /rss_posts/1.xml
  def destroy
    @rss_post = RssPost.find(params[:id])
    @rss_post.destroy

    respond_to do |format|
      format.html { redirect_to(rss_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/rss_posts/_form.html.erb
<%= form_for(@rss_post) do |f| %>
  <% if @rss_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_post.errors.count, "error") %> prohibited this rss_post from being saved:</h2>

      <ul>
      <% @rss_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br />
    <%= f.date_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rss_posts/_link.html.erb
<%= link_to post.title, new_post_read_record_path(:post_id => post.id, :user_id => user_id) %>
<br />
<i>
<%= raw(post.description) %>
</i>
<br />

app/views/rss_posts/show.html.erb
<%= link_to "Sign in as a different user", users_signin_path %>
<%= link_to "Go Back", url_for(:back) %>
<hr>

<p id="notice"><%= notice %></p>

<iframe src="<%= @rss_post.link %>" width="100%" height="100%" />